// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAh6bfpIELVqNUxJNtO8-TVr0bna3mN1WY',
    appId: '1:776710598160:web:632b5d55397bc69109a495',
    messagingSenderId: '776710598160',
    projectId: 'pets-anaimal',
    authDomain: 'pets-anaimal.firebaseapp.com',
    storageBucket: 'pets-anaimal.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOgmImNjB1wW2kuJUQnjGBGpNRHlNZtdk',
    appId: '1:776710598160:android:cadd0299f9919fc309a495',
    messagingSenderId: '776710598160',
    projectId: 'pets-anaimal',
    storageBucket: 'pets-anaimal.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIGJXlhxvVYnMFxM5mtBw9C8GUL2A9Oj4',
    appId: '1:776710598160:ios:959b514a1212589609a495',
    messagingSenderId: '776710598160',
    projectId: 'pets-anaimal',
    storageBucket: 'pets-anaimal.appspot.com',
    iosClientId: '776710598160-i05tshvbmc3di8nrfjda0uhjnno4389o.apps.googleusercontent.com',
    iosBundleId: 'com.example.animalHouse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIGJXlhxvVYnMFxM5mtBw9C8GUL2A9Oj4',
    appId: '1:776710598160:ios:959b514a1212589609a495',
    messagingSenderId: '776710598160',
    projectId: 'pets-anaimal',
    storageBucket: 'pets-anaimal.appspot.com',
    iosClientId: '776710598160-i05tshvbmc3di8nrfjda0uhjnno4389o.apps.googleusercontent.com',
    iosBundleId: 'com.example.animalHouse',
  );
}
